### ISSUE TITLE
Stabilize jawn (1.0.0)

### ISSUE THREAD

**Issue by larsrh** [typelevel/jawn#193]
I think it's time for Jawn to graduate to 1.0.0.

The only pressing issue I see before that can happen is scala.js support (#38), but apart from that, there's not much activity that demands staying in the 0.x series.

Thoughts?

**Comment by travisbrown** [comment]
I had at least a couple of things in mind that I'd like to propose before 1.0.0. I can try to dig them up this week.

**Comment by larsrh** [comment]
I've created a milestone to track this goal.

**Comment by larsrh** [comment]
Anything else we need?

**Comment by non** [comment]
I'm not sure if anyone uses the Jawn AST -- I could imagine cleaning that up a bit (given it's about 6 years old I'd do some things differently now). Not sure that's a high priority though.

**Comment by plokhotnyuk** [comment]
@non If you will decide to keep the Jawn AST then, please, make sure that it does not instantiate Scala's `HashMap`/`HasSet` directly (or indirectly through Scala collection calls like: `toMap`, `keys`, etc.): https://github.com/scala/bug/issues/11203

**Comment by travisbrown** [comment]
I'd be happy to move forward with 1.0, but I think it'd be a good idea to publish a 1.0.0-RC1 first.

**Comment by travisbrown** [comment]
@non @larsrh What do you think about publishing a 1.0.0-RC1? I could do it next week.

**Comment by larsrh** [comment]
Good for me.

**Comment by travisbrown** [comment]
Great! I'll do this tomorrow unless anyone speaks up.

**Comment by julienrf** [comment]
> I'm not sure if anyone uses the Jawn AST

You should be able to see that by looking at the sonatype stats, I believe.

Personally, I like having a small self-contained library that does parsing (to an AST) and pretty-printing.

**Comment by travisbrown** [comment]
@julienrf I can only see the stats since the move to `org.typelevel`, but last month `jawn-ast_2.12` was downloaded 1,932 times vs. `jawn-parser_2.12`'s 142,170.

**Comment by travisbrown** [comment]
One thing that might be an issue is the fact that both play-json and json4s have new minor releases coming out soon-ish and it's not entirely clear to me what their bincompat guarantees are.

Worst case we'd have to split those support modules into their own separately-versioned repos, but we might want to do that before 1.0.0 anyway?

**Comment by rossabaker** [comment]
I think splitting the support modules is the right thing to do.  A release of Downstream Library X should not churn Downstream Library Y, and a missing cross build for Downstream Library X should not block Downstream Library Y.

**Comment by travisbrown** [comment]
@rossabaker Do you think we should do that before 1.0.0? If we publish e.g. jawn-play 1.0.0 and then play-json 2.8 comes out with breaking changes next month, it will immediately need a major version bump (which may be fine).

I don't use these support modules and don't have a strong opinion either way, except that I don't personally want to take on maintaining / publishing several new repos.

**Comment by rossabaker** [comment]
I don't see any reason we can't defer splitting until they become problematic.

**Comment by travisbrown** [comment]
We've now published what I think might be our final release candidate: [1.0.0-RC3](https://github.com/typelevel/jawn/releases/tag/v1.0.0-RC3).

I've published milestone releases using this release candidate for several projects:

* [The Circe core modules](https://github.com/circe/circe/releases/tag/v0.13.0-M2) (including circe-jawn)
* [circe-iteratee](https://github.com/circe/circe-iteratee/releases/tag/v0.13.0-M2)
* [circe-fs2](https://github.com/circe/circe-fs2/releases/tag/v0.13.0-M1)

There are PRs open (with tests passing) for some other projects:

* https://github.com/http4s/jawn-fs2/pull/86
* https://github.com/http4s/http4s/pull/3062

I've also updated some of our internal projects, the [Circe streaming example](https://github.com/circe/circe/pull/1361/files), etc., and haven't turned up any issues. I did make [one minor change](https://github.com/typelevel/jawn/pull/223) since RC3, but it's a small API consistency fix that I don't think needs a new RC.

If nobody complains before then, I'll publish 1.0.0 this weekend.

**Comment by travisbrown** [comment]
It's done! https://github.com/typelevel/jawn/releases/tag/v1.0.0
